fix: FTBFS due to JDK 11 complaining
The following error message occurs when using JDK 11 to compile:

  error: cannot infer type arguments for java.nio.file.SimpleFileVisitor<T>
          new SimpleFileVisitor<>() {
                               ^
  reason: cannot use '<>' with anonymous inner classes